from pydantic import BaseModel, Field
from typing import Optional

class ChatRequest(BaseModel):
    """ Validates incoming streaming queries typed by the user """
    message: str = Field(..., min_length=1, description="The travel query text typed by the traveler")


class ChatResponse(BaseModel):
    """ Shapes conversational output payloads accompanied by dynamic meta-chat buttons """
    bot_response: str = Field(..., description="The conversational text generated by the chatbot")
    show_plan_button: bool = Field(default=False, description="Tells the mobile frontend whether to render the button component")
    meta_plan_data: Optional[dict] = Field(default=None, description="Structured itinerary JSON payloads to map natively")
