from pydantic import BaseModel, Field
from typing import Optional

class ChatRequest(BaseModel):
    """ Validates incoming streaming queries typed by the user """
    message: str = Field(..., min_length=1, description="The travel query text typed by the traveler")


class MetaPlanData(BaseModel):
    """
    STRUCTURED ITINERARY BLUEPRINT CONTRACT:
    Matches the fields your POST /trips manual creation route expects.
    """
    trip_title: str = Field(...,
                            description="An energetic title for the trip generated by the AI (e.g., 'Luxury Hunza Escape')")
    destination: str = Field(..., description="The targeted destination city or valley")
    itinerary_details: str = Field(...,
                                   description="Highly detailed day-by-day text itinerary text compiled from database available rows")
    scope: str = Field(default="history",
                       description="The lifecycle state anchor. Defaults to 'history' so it saves safely to the dashboard")


class ChatResponse(BaseModel):
    """ Shapes conversational output payloads accompanied by dynamic meta-chat buttons """
    bot_response: str = Field(..., description="The conversational text generated by the chatbot")

    # 🖱️ CRITICAL WORKFLOW TRIGGER FLAGS:
    show_plan_button: bool = Field(default=False,
                                   description="Tells the mobile frontend whether to render the 'Save to Dashboard' button component")

    # 💾 THE DISCARDABLE PAYLOAD HOLDER:
    # Stays null while gathering info. If traveler ignores the button, this data is safely dropped from memory.
    meta_plan_data: Optional[MetaPlanData] = Field(default=None,
                                                   description="Structured itinerary payload to map natively to POST /trips")
