import enum
from database import Base
from sqlalchemy import Column, Integer, String, Text, ForeignKey, DateTime, Enum
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func


class TripScopeEnum(str, enum.Enum):
    current = "current"  # The active, ongoing, or upcoming journey layout
    history = "history"  # Completed past adventures written to disk entries


class UserTrips(Base):
    __tablename__ = "user_trips"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="CASCADE"), nullable=False)

    trip_title = Column(String, nullable=False, comment="e.g., '5-Day Hunza Summer Exploration'")
    destination = Column(String, nullable=False, comment="Main regional destination name tag")

    start_date = Column(DateTime(timezone=True), nullable=True)
    end_date = Column(DateTime(timezone=True), nullable=True)

    # Flexible text area mapping out daily route specs generated by traveler or AI
    itinerary_details = Column(Text, nullable=False)

    # 🔄 Dynamic Lifecycle States Monitor
    scope = Column(
        Enum(TripScopeEnum),
        default=TripScopeEnum.current,
        server_default=TripScopeEnum.current.value,
        nullable=False
    )

    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)

    # Relational link directly back to the main traveler profile table row
    user = relationship("Users", back_populates="trips")
